export type SoftwareOrganization = { isOwner: boolean; organization: { id: string; name: string } };
export type SoftwareCustomer = { id: string; name: string; email: string | null; phone: string | null; taxNumber: string | null; status: string };
export type SoftwareProduct = { id: string; sku: string; name: string; description: string | null; priceMinor: number; costMinor: number; currency: string; stockQuantity: number; reorderLevel: number; isActive: boolean };
export type SoftwareReceipt = { id: string; documentId: string; amountMinor: number; currency: string; reference: string | null; receivedAt: string; document?: { number: string; totalMinor: number } };
export type SalesDocument = { id: string; organizationId: string; customerId: string | null; kind: "QUOTE" | "ORDER" | "INVOICE" | "RETURN"; status: string; number: string; currency: string; subtotalMinor: number; taxMinor: number; totalMinor: number; issuedAt: string; dueAt: string | null; notes: string | null; customer: SoftwareCustomer | null; lines: { id: string; productId: string | null; description: string; quantity: number; unitPriceMinor: number; taxRateBps: number; lineTotalMinor: number; product: { id: string; name: string; sku: string } | null }[]; receipts: SoftwareReceipt[] };
export type CrmLead = { id: string; customerId: string | null; name: string; contact: string | null; source: string | null; valueMinor: number | null; currency: string; status: string; nextAction: string | null; customer: SoftwareCustomer | null; updatedAt: string };
export type InventoryMovement = { id: string; productId: string; type: string; quantity: number; note: string | null; referenceType: string | null; occurredAt: string; product: { name: string; sku: string } };
export type SoftwareSupplier = { id: string; name: string; email: string | null; phone: string | null };
export type PurchaseOrder = { id: string; supplierId: string | null; number: string; status: string; currency: string; totalMinor: number; expectedAt: string | null; receivedAt: string | null; supplier: SoftwareSupplier | null; lines: { id: string; description: string; quantity: number; unitCostMinor: number; lineTotalMinor: number; product: SoftwareProduct | null }[] };
export type PosShift = { id: string; status: string; openingCashMinor: number; closingCashMinor: number | null; openedAt: string; closedAt: string | null; sales: { id: string; totalMinor: number; receipts: SoftwareReceipt[] }[] };
export type SoftwareEmployee = { id: string; employeeNumber: string; name: string; email: string | null; roleTitle: string; salaryMinor: number; currency: string; status: string; hiredAt: string };
export type AttendanceRecord = { id: string; date: string; status: string; checkInAt: string | null; checkOutAt: string | null; note: string | null; employee: { name: string; employeeNumber: string } };
export type LeaveRequest = { id: string; employeeId: string; startDate: string; endDate: string; reason: string | null; status: string; employee: { name: string; employeeNumber: string } };
export type PayrollRun = { id: string; periodStart: string; periodEnd: string; status: string; totalGrossMinor: number; totalNetMinor: number; postedAt: string | null; items: { id: string; grossMinor: number; deductionsMinor: number; netMinor: number; employee: { name: string; employeeNumber: string } }[] };
export type PerformanceReview = { id: string; score: number; summary: string; period: string; reviewedAt: string; employee: { name: string; employeeNumber: string } };
export type SoftwareWorkspaceData = {
  company: { id: string; name: string; currentUserIsOwner: boolean; members: { id: string; status: string; isOwner: boolean; role: { key: string; name: string } | null; user: { email: string; profile: { displayName: string | null } | null } }[]; businessPrograms: { id: string; key: string; status: string }[] };
  sales: { customers: SoftwareCustomer[]; products: SoftwareProduct[]; documents: SalesDocument[]; receipts: SoftwareReceipt[] };
  salesSummary: { activeCustomers: number; activeProducts: number; invoiceTotalMinor: number; outstandingMinor: number; quoteCount: number; receivedMinor: number };
  operations: { leads: CrmLead[]; products: SoftwareProduct[]; movements: InventoryMovement[]; suppliers: SoftwareSupplier[]; purchaseOrders: PurchaseOrder[]; posShifts: PosShift[]; projects: { id: string; name: string; status: string; currentPhase: string | null; updatedAt: string }[]; entries: { id: string; type: "INCOME" | "EXPENSE"; amountMinor: number; currency: string; description: string; occurredAt: string }[] };
  operationsSummary: { activeLeads: number; incomeMinor: number; expenseMinor: number; lowStock: number; openPurchases: number; openShift: PosShift | null; profitMinor: number };
  hr: { employees: SoftwareEmployee[]; attendance: AttendanceRecord[]; leaveRequests: LeaveRequest[]; payrollRuns: PayrollRun[]; reviews: PerformanceReview[] };
};

export type SoftwareApiPayload = { success: boolean; message?: string; organizations: SoftwareOrganization[]; workspace: SoftwareWorkspaceData | null };