"use client";

import { Icon } from "@/components/ui/icons";
import type { SoftwareWorkspaceData } from "@/components/software/software-erp-types";
import { buildCrmAnalytics, buildInventoryAnalytics, buildPosAnalytics, buildProjectOperations, buildPurchaseAnalytics } from "@/lib/software/operational-analytics";
import type { SoftwareRouteId } from "@/lib/software/software-routes";
import type { Locale } from "@/types/i18n";

function money(amountMinor: number, currency: string, locale: Locale) {
  return new Intl.NumberFormat(locale === "ar" ? "ar-SA" : "en-US", { currency, style: "currency" }).format(amountMinor / 100);
}

function date(value: string | null, locale: Locale) {
  return value ? new Intl.DateTimeFormat(locale === "ar" ? "ar-SA" : "en-GB", { dateStyle: "medium" }).format(new Date(value)) : "—";
}

function activityLabel(action: string, ar: boolean) {
  if (action.endsWith("lead.created")) return ar ? "إنشاء فرصة" : "Lead created";
  if (action.endsWith("lead.status.updated")) return ar ? "تحديث مرحلة" : "Stage updated";
  return action.replace("software.crm.", "").replaceAll(".", " ");
}

export function SoftwareAnalyticsOverview({ locale, routeId, workspace }: { locale: Locale; routeId: SoftwareRouteId; workspace: SoftwareWorkspaceData }) {
  const ar = locale === "ar";
  if (routeId === "inventory") {
    const analytics = buildInventoryAnalytics(workspace);
    return <section className="software-analytics" data-software-analytics="inventory">
      <section className="software-erp__signals"><article><span>SKU</span><strong>{analytics.itemCount}</strong><small>{ar ? "أصناف مسجلة" : "Recorded items"}</small></article><article><span>QTY</span><strong>{analytics.unitCount}</strong><small>{ar ? "وحدات حالية" : "Current units"}</small></article><article><span>LOW</span><strong>{analytics.lowStockCount}</strong><small>{ar ? "تحتاج مراجعة طلب" : "Need reorder review"}</small></article><article><span>30D</span><strong>{analytics.recentMovementCount}</strong><small>{ar ? `حركات · صافي ${analytics.recentNetQuantity}` : `movements · net ${analytics.recentNetQuantity}`}</small></article></section>
      <div className="software-analytics__grid"><section><header><div><span>VALUE</span><h2>{ar ? "قيمة المخزون بالتكلفة" : "Inventory value at cost"}</h2></div><small>{ar ? "الكمية الحالية × تكلفة الصنف" : "Current quantity × product cost"}</small></header>{analytics.values.length ? <div className="software-analytics__values">{analytics.values.map((value) => <article key={value.currency}><span>{value.currency}</span><strong>{money(value.costMinor, value.currency, locale)}</strong><small>{ar ? `تكلفة النقص حتى حد الطلب: ${money(value.reorderMinor, value.currency, locale)}` : `Cost to reach reorder level: ${money(value.reorderMinor, value.currency, locale)}`}</small></article>)}</div> : <p>{ar ? "لا توجد أصناف مسجلة." : "No products recorded."}</p>}</section><section><header><div><span>REORDER</span><h2>{ar ? "قائمة إعادة الطلب" : "Reorder review"}</h2></div><small>{ar ? "لا يُنشأ طلب تلقائيًا" : "No automatic order is placed"}</small></header>{analytics.reorderItems.length ? <div className="software-analytics__list">{analytics.reorderItems.map((item) => <article key={item.id}><div><strong>{item.name}</strong><small>{item.sku} · {ar ? "الحالي" : "Current"} {item.stockQuantity} / {ar ? "الحد" : "Level"} {item.reorderLevel}</small></div><span>{item.shortage ? money(item.reorderCostMinor, item.currency, locale) : (ar ? "راجع الحد" : "Review level")}</span></article>)}</div> : <p>{ar ? "لا توجد أصناف عند حد إعادة الطلب." : "No items are at their reorder level."}</p>}</section></div>
      <section className="software-analytics__count"><header><div><span>COUNT</span><h2>{ar ? "حالة الجرد" : "Inventory count status"}</h2></div><small>{ar ? "يعتمد على آخر حركة تسوية يدوية خلال 30 يومًا" : "Based on the latest manual adjustment within 30 days"}</small></header><div>{analytics.countRows.map((row) => <article key={row.id}><div><strong>{row.name}</strong><small>{row.sku}</small></div><span>{date(row.lastCountedAt, locale)}</span><b className={row.status === "COUNTED" ? "is-ready" : "is-due"}>{row.status}</b></article>)}</div></section>
    </section>;
  }

  if (routeId === "crm") {
    const analytics = buildCrmAnalytics(workspace);
    return <section className="software-analytics" data-software-analytics="crm">
      <section className="software-erp__signals"><article><span>LEAD</span><strong>{workspace.operations.leads.length}</strong><small>{ar ? "فرص مسجلة" : "Recorded leads"}</small></article><article><span>LINK</span><strong>{analytics.linkedCustomers}</strong><small>{ar ? "مرتبطة بعملاء" : "Linked customers"}</small></article><article><span>NEXT</span><strong>{analytics.pendingActions}</strong><small>{ar ? "خطوات تالية مفتوحة" : "Open next actions"}</small></article><article><span>ACT</span><strong>{workspace.operations.crmActivities.length}</strong><small>{ar ? "أحداث مدققة" : "Audited activities"}</small></article></section>
      <div className="software-analytics__grid"><section><header><div><span>FORECAST</span><h2>{ar ? "توقع خط المبيعات" : "Pipeline forecast"}</h2></div><small>{ar ? "تقدير تخطيطي، لا إيراد محقق" : "Planning estimate, not realized revenue"}</small></header>{analytics.currencies.length ? <div className="software-crm-forecast">{analytics.currencies.map((forecast) => <article key={forecast.currency}><header><span>{forecast.currency}</span><strong>{forecast.leadCount} {ar ? "فرص" : "leads"}</strong></header><dl><div><dt>{ar ? "مفتوح" : "Open pipeline"}</dt><dd>{money(forecast.openMinor, forecast.currency, locale)}</dd></div><div><dt>{ar ? "موزون" : "Weighted estimate"}</dt><dd>{money(forecast.weightedMinor, forecast.currency, locale)}</dd></div><div><dt>{ar ? "مكسب" : "Won"}</dt><dd>{money(forecast.securedMinor, forecast.currency, locale)}</dd></div></dl></article>)}</div> : <p>{ar ? "أضف قيمة للفرص لعرض التوقع." : "Add lead values to render the forecast."}</p>}<p className="software-analytics__formula">{ar ? "الأوزان: جديد 10% · مؤهل 35% · تم التواصل 65% · مكسب 100% · مفقود 0%. راجعها وفق نموذج مبيعاتك." : "Weights: New 10% · Qualified 35% · Contacted 65% · Won 100% · Lost 0%. Review them against your sales model."}</p></section><section><header><div><span>ACTIVITY</span><h2>{ar ? "سجل الأنشطة" : "Activity log"}</h2></div><small>{ar ? "المصدر: سجل التدقيق" : "Source: audit log"}</small></header>{workspace.operations.crmActivities.length ? <div className="software-analytics__activity">{workspace.operations.crmActivities.slice(0, 8).map((activity) => { const lead = workspace.operations.leads.find((item) => item.id === activity.entityId); return <article key={activity.id}><Icon name={activity.action.endsWith("created") ? "plus" : "activity"} /><div><strong>{activityLabel(activity.action, ar)}</strong><small>{lead?.name ?? activity.entityId ?? "CRM"} · {date(activity.createdAt, locale)}</small></div>{activity.metadata && typeof activity.metadata === "object" && "status" in activity.metadata ? <span>{String(activity.metadata.status)}</span> : null}</article>; })}</div> : <p>{ar ? "لا توجد أنشطة مدققة بعد." : "No audited activities yet."}</p>}</section></div>
    </section>;
  }
  if (routeId === "projects") {
    const analytics = buildProjectOperations(workspace);
    return <section className="software-analytics" data-software-analytics="projects">
      <section className="software-erp__signals"><article><span>LIVE</span><strong>{analytics.activeProjects}</strong><small>{ar ? "مشاريع نشطة" : "Active projects"}</small></article><article><span>WORK</span><strong>{analytics.completedPhases}</strong><small>{ar ? "مراحل عمل مكتملة" : "Completed work phases"}</small></article><article><span>TEAM</span><strong>{analytics.teamSeats}</strong><small>{ar ? "عضويات مشاريع" : "Project memberships"}</small></article><article><span>PLAN</span><strong>{analytics.budgetedProjects}</strong><small>{ar ? "خطط مالية محفوظة" : "Saved financial plans"}</small></article></section>
      <section className="software-project-operations"><header><div><span>DELIVERY</span><h2>{ar ? "المراحل والوقت والميزانية والفريق" : "Work phases, time, budget, and team"}</h2></div><small>{ar ? "المراحل هي وحدات العمل الفعلية؛ لا يوجد نموذج مهام مستقل بعد." : "Phases are the current work units; no separate task model exists yet."}</small></header>{analytics.projects.length ? <div>{analytics.projects.map((project) => <article key={project.id}><header><div><strong>{project.name}</strong><small>{project.status} · {project.currentPhase ?? "—"}</small></div><span>{project.completionPercent}%</span></header><div className="software-project-operations__track"><i style={{ width: `${project.completionPercent}%` }} /></div><dl><div><dt>{ar ? "الوقت" : "Time"}</dt><dd>{project.startedAt ? `${date(project.startedAt, locale)} — ${project.phases.every((phase) => phase.status === "COMPLETED") ? date(project.phases.at(-1)?.completedAt ?? null, locale) : (ar ? "مستمر" : "Ongoing")}` : (ar ? "لم يبدأ" : "Not started")}</dd></div><div><dt>{ar ? "الميزانية" : "Budget"}</dt><dd>{project.initialInvestment === null ? (ar ? "لا توجد خطة مالية" : "No financial plan") : `${money(Math.round(project.initialInvestment * 100), project.currency, locale)} · v${project.financialPlan?.version}`}</dd></div><div><dt>{ar ? "الفريق" : "Team"}</dt><dd>{project.members.length ? project.members.map((member) => `${member.user.profile?.displayName || (ar ? "عضو" : "Member")} (${member.role})`).join(" · ") : (ar ? "لا أعضاء" : "No members")}</dd></div></dl><div className="software-project-operations__phases">{project.phases.map((phase) => <span className={`is-${phase.status.toLocaleLowerCase()}`} key={phase.id}>{phase.sequence}. {phase.title}</span>)}</div></article>)}</div> : <p>{ar ? "لا توجد مشاريع مرتبطة بالمنظمة." : "No projects are linked to this organization."}</p>}</section>
    </section>;
  }
  if (routeId === "purchases") {
    const analytics = buildPurchaseAnalytics(workspace);
    return <section className="software-analytics" data-software-analytics="purchases">
      <section className="software-erp__signals"><article><span>SUP</span><strong>{analytics.supplierCount}</strong><small>{ar ? "موردون" : "Suppliers"}</small></article><article><span>PO</span><strong>{analytics.orderCount}</strong><small>{ar ? "طلبات شراء" : "Purchase orders"}</small></article><article><span>OPEN</span><strong>{analytics.openCount}</strong><small>{ar ? "طلبات مفتوحة" : "Open orders"}</small></article><article><span>LATE</span><strong>{analytics.overdueCount}</strong><small>{ar ? "متأخرة عن المتوقع" : "Past expected date"}</small></article></section>
      <div className="software-analytics__grid"><section><header><div><span>VALUE</span><h2>{ar ? "قيمة الطلبات" : "Purchase order value"}</h2></div><small>{ar ? "مفصولة حسب العملة" : "Separated by currency"}</small></header><div className="software-analytics__values">{analytics.totals.map((total) => <article key={total.currency}><span>{total.currency}</span><strong>{money(total.openMinor, total.currency, locale)}</strong><small>{ar ? `مستلم: ${money(total.receivedMinor, total.currency, locale)}` : `Received: ${money(total.receivedMinor, total.currency, locale)}`}</small></article>)}</div></section><section><header><div><span>INVOICES</span><h2>{ar ? "فواتير الموردين" : "Supplier invoices"}</h2></div><small>NOT_CONNECTED</small></header><div className="software-analytics__unavailable"><Icon name="lock" /><strong>{ar ? "لا يوجد دفتر فواتير موردين مستقل" : "No separate supplier invoice ledger"}</strong><p>{ar ? "الطلب والاستلام والقيد المالي يعملون، لكن رقم فاتورة المورد والاستحقاق والدفع غير ممثلة؛ لن نعرضها كبيانات مكتملة." : "Ordering, receiving, and financial posting work, but supplier invoice number, due date, and settlement are not modeled and are not presented as complete."}</p></div></section></div>
    </section>;
  }
  if (routeId === "pos") {
    const analytics = buildPosAnalytics(workspace);
    return <section className="software-analytics" data-software-analytics="pos">
      <section className="software-erp__signals"><article><span>SHIFT</span><strong>{analytics.shiftCount}</strong><small>{ar ? "ورديات" : "Shifts"}</small></article><article><span>OPEN</span><strong>{analytics.openCount}</strong><small>{ar ? "مفتوحة" : "Open"}</small></article><article><span>SALE</span><strong>{analytics.saleCount}</strong><small>{ar ? "عمليات بيع" : "Sales"}</small></article><article><span>PAY</span><strong>{analytics.paymentCount}</strong><small>{ar ? "مدفوعات" : "Payments"}</small></article></section>
      <div className="software-analytics__grid"><section><header><div><span>PAYMENTS</span><h2>{ar ? "حجم المدفوعات" : "Payment volume"}</h2></div><small>{ar ? "من سندات قبض POS" : "From POS receipts"}</small></header><div className="software-analytics__values">{analytics.paymentTotals.map((total) => <article key={total.currency}><span>{total.currency}</span><strong>{money(total.amountMinor, total.currency, locale)}</strong><small>{ar ? "مدفوعات مسجلة" : "Recorded payments"}</small></article>)}</div></section><section><header><div><span>BRANCHES</span><h2>{ar ? "الفروع" : "Branches"}</h2></div><small>{analytics.branchesConnected ? "CONNECTED" : "NOT_CONFIGURED"}</small></header>{workspace.company.softwareBranches.length ? <div className="software-analytics__list">{workspace.company.softwareBranches.map((branch) => <article key={branch.id}><div><strong>{branch.name}</strong><small>{branch.code} · {[branch.city, branch.countryCode].filter(Boolean).join(" · ")}</small></div><span>{branch.status}</span></article>)}</div> : <div className="software-analytics__unavailable"><Icon name="building" /><strong>{ar ? "لا توجد فروع بعد" : "No branches configured"}</strong><p>{ar ? "أنشئ فرعًا من إدارة الشركات ثم عيّنه افتراضيًا لربط الورديات الجديدة." : "Create a branch in Company management and set it as default to attribute new shifts."}</p></div>}</section></div>
      <section className="software-pos-reconciliation"><header><div><span>RECONCILIATION</span><h2>{ar ? "مطابقة الورديات المغلقة" : "Closed-shift reconciliation"}</h2></div><small>{ar ? "النقد الافتتاحي + المقبوضات = المتوقع" : "Opening cash + receipts = expected cash"}</small></header>{analytics.reconciliation.length ? <div>{analytics.reconciliation.map((row) => <article key={row.id}><div><strong>{row.branch ? `${row.branch.code} · ${row.branch.name}` : (ar ? "بلا فرع" : "Unassigned")}</strong><small>{date(row.openedAt, locale)} · {row.currency} · {row.reliable ? (ar ? "عملة واحدة" : "Single currency") : (ar ? "عملات متعددة" : "Mixed currencies")}</small></div><span>{row.expectedMinor === null ? "—" : money(row.expectedMinor, row.currency, locale)}</span><span>{row.actualMinor === null ? "—" : money(row.actualMinor, row.currency, locale)}</span><b className={row.varianceMinor === 0 ? "is-ready" : "is-due"}>{row.varianceMinor === null ? "UNAVAILABLE" : money(row.varianceMinor, row.currency, locale)}</b></article>)}</div> : <p>{ar ? "لا توجد ورديات مغلقة للمطابقة." : "No closed shifts are available for reconciliation."}</p>}</section>
    </section>;
  }
  return null;
}