export type AdminOperationGroup = "admin" | "factory" | "academy" | "organization" | "missions" | "intelligence" | "models" | "finance" | "observability" | "reports";

const route = (path: string, title: string, kind: string, group: AdminOperationGroup) => ({ path, title, kind, group });

export const ADMIN_OPERATION_ROUTES = [
  route("/admin", "مركز قيادة Jenan PRO", "command", "admin"),
  route("/admin/operations", "مركز العمليات الحي", "command", "admin"),
  route("/admin/users", "إدارة المستخدمين", "list", "admin"),
  route("/admin/subscriptions", "الاشتراكات والخطط", "list", "admin"),
  route("/admin/services", "الخدمات والأقسام", "matrix", "admin"),
  route("/admin/rbac", "الأدوار والصلاحيات RBAC", "matrix", "admin"),
  route("/admin/audit", "سجل التدقيق", "timeline", "admin"),
  route("/robots/factory", "مصنع الروبوتات", "factory", "factory"),
  route("/robots/factory/create-batch", "إنشاء دفعة روبوتات", "wizard", "factory"),
  route("/robots/factory/batches", "دفعات مصنع الروبوتات", "list", "factory"),
  route("/robots/factory/batches/sample", "تفاصيل دفعة روبوتات", "detail", "factory"),
  route("/robots/factory/genetics", "قواعد التوليد والاختيار", "network", "factory"),
  route("/robots/registry", "سجل هويات الروبوتات", "registry", "factory"),
  route("/robots/profile/sample", "ملف الروبوت", "profile", "factory"),
  route("/robot-academy", "أكاديمية روبوتات Jenan PRO", "academy", "academy"),
  route("/robot-academy/batches", "دفعات الأكاديمية", "list", "academy"),
  route("/robot-academy/batches/sample", "مسار دفعة داخل الأكاديمية", "timeline", "academy"),
  route("/robot-academy/curriculum", "المناهج والمسارات", "academy", "academy"),
  route("/robot-academy/theory", "الدراسة النظرية", "learning", "academy"),
  route("/robot-academy/practical", "التدريب العملي", "learning", "academy"),
  route("/robot-academy/exams", "مركز الاختبارات", "exam", "academy"),
  route("/robot-academy/exams/sample", "تفاصيل اختبار", "exam", "academy"),
  route("/robot-academy/results/sample", "نتيجة روبوت", "profile", "academy"),
  route("/robot-academy/graduation", "التخرج والتوزيع", "academy", "academy"),
  route("/robot-academy/elimination", "الاستبعاد وإعادة التأهيل", "list", "academy"),
  route("/robot-academy/specializations", "التخصصات والمهارات", "matrix", "academy"),
  route("/robot-academy/geography", "التخصص الجغرافي", "map", "academy"),
  route("/robot-academy/reports", "تقارير الأكاديمية", "report-center", "academy"),
  route("/robot-org", "الهيكل الإداري للروبوتات", "org", "organization"),
  route("/robot-org/workers", "الروبوتات الموظفة", "list", "organization"),
  route("/robot-org/supervisors", "المشرفون", "list", "organization"),
  route("/robot-org/managers", "المديرون", "list", "organization"),
  route("/robot-org/supreme-committee", "اللجنة العليا — 50 روبوت", "committee", "organization"),
  route("/robot-org/supreme-committee/review/sample", "ملف مراجعة اللجنة", "committee", "organization"),
  route("/robot-org/escalations", "مركز التصعيدات", "list", "organization"),
  route("/missions", "Mission Control — مركز المهام", "mission", "missions"),
  route("/missions/create", "إنشاء مهمة", "wizard", "missions"),
  route("/missions/queue", "طابور المهام", "queue", "missions"),
  route("/missions/sample", "تفاصيل المهمة", "mission-detail", "missions"),
  route("/missions/sample/dependencies", "اعتماديات المهمة", "network", "missions"),
  route("/missions/sample/retry-fallback", "Retry & Fallback", "timeline", "missions"),
  route("/missions/sample/approvals", "الموافقات والتصعيد", "timeline", "missions"),
  route("/missions/sample/evidence", "Evidence Pack — حزمة الأدلة", "evidence", "missions"),
  route("/missions/sample/cost", "تكلفة المهمة", "finance", "missions"),
  route("/missions/reports", "تقارير المهام", "report-center", "missions"),
  route("/intelligence", "مركز الذكاء", "intelligence", "intelligence"),
  route("/intelligence/knowledge", "المعرفة المشتركة", "knowledge", "intelligence"),
  route("/intelligence/experiences", "مكتبة الخبرات", "knowledge", "intelligence"),
  route("/intelligence/learning-logs", "Learning Logs", "timeline", "intelligence"),
  route("/intelligence/evidence", "قاعدة الأدلة", "evidence", "intelligence"),
  route("/intelligence/reviews", "مراجعة واعتماد المعرفة", "committee", "intelligence"),
  route("/intelligence/versions", "الإصدارات وRollback", "timeline", "intelligence"),
  route("/intelligence/skills", "سجل المهارات", "matrix", "intelligence"),
  route("/models", "Model Registry", "registry", "models"),
  route("/models/router", "Model Router", "network", "models"),
  route("/models/executions", "Model Executions", "list", "models"),
  route("/tools", "Tool Registry", "registry", "models"),
  route("/tools/permissions", "صلاحيات الأدوات", "matrix", "models"),
  route("/tools/executions", "Tool Executions", "list", "models"),
  route("/finance", "المركز المالي التشغيلي", "finance", "finance"),
  route("/finance/revenue", "الإيرادات", "finance", "finance"),
  route("/finance/costs", "التكاليف", "finance", "finance"),
  route("/finance/ai-costs", "تكاليف الذكاء", "finance", "finance"),
  route("/finance/service-profitability", "ربحية الخدمات", "matrix", "finance"),
  route("/finance/ledger", "Cost Ledger", "list", "finance"),
  route("/finance/reports", "التقارير المالية التشغيلية", "report-center", "finance"),
  route("/observability", "Observability Center", "command", "observability"),
  route("/observability/workers", "Workers", "queue", "observability"),
  route("/observability/queues", "Queues", "queue", "observability"),
  route("/observability/health", "صحة الأنظمة", "command", "observability"),
  route("/observability/logs", "السجلات", "list", "observability"),
  route("/observability/alerts", "التنبيهات والحوادث", "list", "observability"),
  route("/observability/backups", "النسخ الاحتياطية", "timeline", "observability"),
  route("/admin/reports", "مركز التقارير العليا", "report-center", "reports"),
  route("/admin/reports/robots", "تقرير أداء الروبوتات", "report", "reports"),
  route("/admin/reports/academy", "تقرير أكاديمية الروبوتات", "report", "reports"),
  route("/admin/reports/missions", "تقرير المهام", "report", "reports"),
  route("/admin/reports/intelligence", "تقرير مركز الذكاء", "report", "reports"),
  route("/admin/reports/finance", "التقرير المالي التشغيلي", "report", "reports"),
  route("/admin/reports/system", "تقرير صحة النظام", "report", "reports"),
] as const;

export type AdminOperationRoute = (typeof ADMIN_OPERATION_ROUTES)[number];

export function findAdminOperationRoute(path: string) {
  return ADMIN_OPERATION_ROUTES.find((definition) => definition.path === path) ?? null;
}